export const GET_ALL_CATEGORIES_INDEPARTMENT = 'GET_ALL_CATEGORIES_IN_DEPARTMENT';
export const GET_ALL_CATEGORIES_INDEPARTMENT_ERROR = 'GET_ALL_CATEGORIES_IN_DEPARTMENT_ERROR';
export const GET_ALL_CATEGORIES_INDEPARTMENT_SUCCESS = 'GET_ALL_CATEGORIES_IN_DEPARTMENT_SUCCESS';


export const getAllCategoriesInDepartment = (data) => (
  {
    type: GET_ALL_CATEGORIES_INDEPARTMENT,
    payload: data
});
