export const GET_ALL_PRODUCTS_INCATEGORY = 'GET_ALL_PRODUCTS_INCATEGORY';
export const GET_ALL_PRODUCTS_INCATEGORY_ERROR = 'GET_ALL_PRODUCTS_INCATEGORY_ERROR';
export const GET_ALL_PRODUCTS_INCATEGORY_SUCCESS = 'GET_ALL_PRODUCTS_INCATEGORY_SUCCESS';


export const getAllProductsInCategory = (data) => (
  {
    type: GET_ALL_PRODUCTS_INCATEGORY,
    payload: data
});
